apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-eyjw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-mifu-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-eyjw@sha256:b8aeebce3a72aa137e6129a512c0eceb70be7171c5c458f842fc9ed2ffb1b042
        name: my-go
        resources: {}
status: {}
