apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-suop
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-mifu-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-suop@sha256:faee977666687a690a13e628521e417bf6cfa741a7451208bcac7b71ef302502
        name: my-nodejs
        resources: {}
status: {}
