apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-4k57
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-mifu-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-4k57@sha256:39ab2cb02cac175a137ba0e055c2300c1833bc00602b988472510b381a76651f
        name: my-python
        resources: {}
status: {}
